//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denghikiemtra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeNghiEntities : DbContext
    {
        public DeNghiEntities()
            : base("name=DeNghiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_DeNghiKiemTraOnline> tbl_DeNghiKiemTraOnline { get; set; }
        public virtual DbSet<tbl_DeNghiKiemTra> tbl_DeNghiKiemTra { get; set; }
    }
}
