//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denghikiemtra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeNghiKiemTraOnline
    {
        public int STT { get; set; }
        public string Ten { get; set; }
        public string DiaChi { get; set; }
        public string Phuong { get; set; }
        public string Quan { get; set; }
        public string LyDo { get; set; }
        public string HinhAnh { get; set; }
        public int TrangThai { get; set; }
    }
}
