//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denghikiemtra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeNghiKiemTra
    {
        public int STT { get; set; }
        public string Tên { get; set; }
        public Nullable<System.DateTime> Ngày_đăng_ký { get; set; }
        public string Phường { get; set; }
        public string Quận { get; set; }
        public string Địa_chỉ { get; set; }
    }
}
